# Generated by Django 4.0b1 on 2022-05-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentecobre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='glosario',
            name='urlEn',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='glosario',
            name='urlEs',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
