# Generated by Django 4.0b1 on 2022-05-19 18:21

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mentecobre', '0002_glosario_urlen_glosario_urles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageidEn', models.IntegerField(blank=True, null=True)),
                ('pageidEs', models.IntegerField(blank=True, null=True)),
                ('tituloEn', models.CharField(blank=True, max_length=200, null=True)),
                ('tituloEs', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('CU', 'Cultura'), ('EVT', 'Eventos y eras'), ('FDV', 'Formas de vida'), ('LIB', 'Libros'), ('LOC', 'Localizaciones'), ('MG', 'Magia'), ('PJ', 'Personajes'), ('OBJ', 'Objetos y materiales'), ('ORG', 'Organización'), ('FAM', 'Familia'), ('MUL', 'multimedia'), ('WIKI', 'wiki/otros'), ('DIS', 'Disambiguación'), ('RD', 'Redirección'), ('SUB', 'Subpágina')], max_length=4, null=True)),
                ('prioridad', models.CharField(blank=True, choices=[('1', 'Alta'), ('2', 'Media'), ('3', 'Baja'), ('4', 'TBD'), ('5', 'Siraya')], max_length=1, null=True)),
                ('fechaasignado', models.DateField(blank=True, null=True)),
                ('cita', models.CharField(blank=True, choices=[('Y', 'Sí'), ('N', 'No')], max_length=1, null=True)),
                ('traducido', models.CharField(blank=True, choices=[('Y', 'Sí'), ('F', 'Falta Cita'), ('O', 'On Hold')], max_length=1, null=True)),
                ('fechatraducido', models.DateField(blank=True, null=True)),
                ('revisado', models.CharField(blank=True, choices=[('Y', 'Sí')], max_length=1, null=True)),
                ('fechaasignadorevisor', models.DateField(blank=True, null=True)),
                ('fecharevisado', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('universo', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('C', 'Cosmere'), ('M', 'Mistborn'), ('S', 'Stormlight'), ('A', 'Aliento'), ('E', 'Elantris'), ('AB', 'Arena Blanca'), ('B', 'Brandon'), ('FU', 'Fuera Universo'), ('OH', 'Otras Historias'), ('R', 'Rithmatista'), ('RT', 'Rueda del Tiempo'), ('CT', 'Citoverso'), ('RK', 'Reckoners'), ('SS', 'Sombras por Silencio'), ('AL', 'Alcatraz'), ('L', 'Legion'), ('SO', 'Sexto del Ocaso'), ('AE', 'Alma del Emperador')], max_length=45, null=True)),
                ('urldrive', models.URLField(blank=True, null=True)),
                ('urlEn', models.URLField(blank=True, null=True)),
                ('urlEs', models.URLField(blank=True, null=True)),
                ('fechacambiosEn', models.DateField(blank=True, null=True)),
                ('revisor', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Revisores'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='revisor', to='mentecobre.usuario')),
                ('traductor', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Traductores'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='traductor', to='mentecobre.usuario')),
            ],
        ),
    ]
