# Generated by Django 4.0b1 on 2022-05-19 22:01

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mentecobre', '0003_articulos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='universo',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('A', 'Aliento de los diosos'), ('AB', 'Arena Blanca'), ('AE', 'El alma del emperador'), ('AL', 'Alcatraz'), ('C', 'Cosmere'), ('CT', 'Citoverso'), ('E', 'Elantris'), ('FU', 'Fuera del universo'), ('L', 'Legión'), ('M', 'Nacidos de la bruma'), ('OH', 'Otras Historias'), ('R', 'Rithmatista'), ('RK', 'Reckoners'), ('RT', 'Rueda del Tiempo'), ('S', 'Archivo de las tormentas'), ('SO', 'Sexto del Ocaso'), ('SS', 'Sombras por silencio')], max_length=43, null=True),
        ),
    ]
