# Generated by Django 4.0.4 on 2022-06-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentecobre', '0006_articulos_enlacecopperen_alter_glosario_universo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
